"""refine users schema

Revision ID: 4519f661ae26
Revises: 8fd0d6965da1
Create Date: 2026-02-27 07:04:16.982335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4519f661ae26'
down_revision: Union[str, Sequence[str], None] = '8fd0d6965da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # Ensure UUID generation is available.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # Convert integer IDs to UUIDs (assign new UUIDs for existing rows).
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN id TYPE UUID USING gen_random_uuid()")
    op.execute("DROP SEQUENCE IF EXISTS users_id_seq")
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    # Recreate integer PK (IDs will be reassigned).
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_pkey")
    op.execute("ALTER TABLE users ADD COLUMN id_int SERIAL")
    op.execute("ALTER TABLE users DROP COLUMN id")
    op.execute("ALTER TABLE users RENAME COLUMN id_int TO id")
    op.execute("ALTER TABLE users ADD PRIMARY KEY (id)")
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
