"""add category

Revision ID: 5569bec1907c
Revises: 97a11a5f2459
Create Date: 2026-03-07 19:57:59.799160
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5569bec1907c'
down_revision = '97a11a5f2459'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(length=255), nullable=False, server_default='General'))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
