"""add image_url to products

Revision ID: 97a11a5f2459
Revises: f6122e526cd8
Create Date: 2026-03-07 19:32:35.050004
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97a11a5f2459'
down_revision = 'f6122e526cd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
