"""add seller_id to products

Revision ID: f6122e526cd8
Revises: f67c99629458
Create Date: 2026-03-05 17:05:17.994420
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6122e526cd8'
down_revision = 'f67c99629458'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###
